[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ClassBook"
authors = [{name = "The ClassBook Devloppers", email = "classbook.dev@outlook.fr"}]
dynamic = ["version", "description"]
